[FTC_Artifactory_Agumbe_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/agumbe-5.1.0/candidate/builds/

[FTC_Artifactory_Agumbe_Staging_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/agumbe-5.1.0/staging/builds/

[FTC_Artifactory_SO_Gen5_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/so-gen5/candidate/builds

[FTC_Artifactory_SO_Gen5_Staging_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/so-gen5/staging/builds

[FTC_Artifactory_SO_Gen5_Pre-Releases]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/so-gen5/pre-releases

[FTC_Artifactory_Corgi_4.3.9_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/corgi-4.3.9/candidate/builds

[FTC_Artifactory_Corgi_4.3.11_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/corgi-4.3.11/candidate/builds

[FTC_Artifactory_Corgi_4.3.13_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/corgi-4.3.13/candidate/builds

[FTC_Artifactory_Badami_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/badami-5.2.0/candidate/builds

[FTC_Artifactory_Coorg_5.3.0_Candidate_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/coorg-5.3.0/candidate/builds

[FTC_Artifactory_Coorg_5.3.0_Staging_Builds]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/coorg-5.3.0/staging/builds

[FTC_Artifactory_Coorg_5.3.0_Pre-Releases]
type = http
url = https://ftcrepo.ftc.storage.hpecorp.net/artifactory/targets/coorg-5.3.0/pre-releases